<a href="https://colab.research.google.com/github/yohan1234/Numpy/blob/main/Numpy_%EA%B8%B0%EB%B3%B8_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [4]:
array2 = np.zeros((4, 4), dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
array3 = np.ones((3,3), dtype = str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [10]:
import numpy as np
array4 = np.random.randint(0, 10, (3, 3))
print(array4)

[[5 0 1]
 [8 8 8]
 [9 3 9]]


In [11]:
array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[[-0.61688969 -1.69141354  1.20973743]
 [ 0.49545137 -0.29661302  0.65641745]
 [ 1.69079932  0.1985663  -1.12199476]]


In [14]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)

(6,)
[1 2 3 4 5 6]


In [15]:
array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape((2, 2))
print(array2)

[[1 2]
 [3 4]]


In [21]:
array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)

print(array1)
print(array2)

array3 = np.concatenate([array1, array2])
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [22]:
array1 = np.arange(4).reshape(1, 4)
array2 = np.arange(8).reshape(2, 4)

print(array1)
print(array2)

array3 = np.concatenate([array1, array2], axis = 0)
print(array3)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [25]:
array = np.arange(8).reshape(2, 4)
left, right = np.split(array, [2], axis = 1)
print(left.shape)
print(right.shape)
print(array)

(2, 2)
(2, 2)
[[0 1 2 3]
 [4 5 6 7]]


In [27]:
array = np.random.randint(1, 10, size=4).reshape(2,2)
print(array)

[[3 5]
 [8 6]]


In [28]:
result_array = array * 10
print(result_array)

[[30 50]
 [80 60]]


In [29]:
array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)

array3 = array1 + array2
print(array3)

[[0 2]
 [2 4]]


In [31]:
array1 = np.arange(0, 8).reshape(2, 4)
array2 = np.arange(0, 8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
array4 = np.arange(0, 4).reshape(4, 1)


print(array3+array4)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [39]:
array1 = np.arange(16).reshape(4, 4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [42]:
array = np.arange(16).reshape(4,4)

print("최대값: ", np.max(array))

print("합계: ", np.sum(array, axis=1))

최대값:  15
합계:  [ 6 22 38 54]


In [4]:
array = np.arange(0, 10)
np.save('saved.npy', array)

In [5]:
result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1=array1, array2=array2)

data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']

print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [12]:
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print(array)
array.sort(axis=0)
print(array)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


In [13]:
array = np.linspace(0, 10, 5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


In [15]:
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))

[[4 9 6]
 [3 3 7]]


In [16]:
array1 = np.arange(0, 10)
array2 = array1
array2[0] = 99
print(array1)

[99  1  2  3  4  5  6  7  8  9]


In [17]:
array1 = np.arange(0, 10)
array2 = array1.copy()
array2[0] = 99
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
array = np.array([1, 1, 2, 2, 3, 3, 4])
print(np.unique(array))

[1 2 3 4]
